name: Solar System Worflow

on:
  workflow_dispacth:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
    unit-testing:
      name: unit testing
      runs-on: ubuntu-latest
      
      steps:

      - name: Checkout Repository
      - uses: actions/checkout@v4
      
      - name: Setup NodeJS version - 18
      - uses: actions/setup-node@v3
          with:
          node-version: 18

      - name: Available expression contexts: github, inputs, vars, needs, starategy, matrix, secrets, steps, job,
        run: runner, env

      - name: Available expression functions: hashFiles
        run: npm test

