name: Solar System Worflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest
        

        
        
        

      
            
        

